/**
 * ============================================================================
 * JULIAN VANCE — PORTFOLIO & CASE STUDIES
 * Pure Vanilla JavaScript (ES6+) · Zero External Dependencies · GitHub Pages Ready
 * ============================================================================
 */

(function () {
  'use strict';

  /* --------------------------------------------------------------------------
   * 1. STORAGE KEYS & DEFAULT PORTFOLIO DATA
   * -------------------------------------------------------------------------- */
  const STORAGE_KEYS = {
    THEME: 'jv_portfolio_theme_v1',
    PROJECTS: 'jv_portfolio_projects_v1',
    INQUIRIES: 'jv_portfolio_inquiries_v1'
  };

  const DEFAULT_PROJECTS = [
    {
      id: 'chronos-engine',
      title: 'Chronos Distributed Time-Series Engine',
      category: 'systems',
      categoryLabel: 'Systems & Infrastructure',
      year: 2026,
      impactRank: 1,
      featured: true,
      bentoSpan: 'bento-wide',
      image: './assets/images/project-chronos.svg',
      stack: 'Rust · WebAssembly · Arrow IPC · SIMD',
      summary: 'High-throughput columnar storage and browser-side WebAssembly query engine sustaining 1.8M writes/sec with 4.2ms p99 latency.',
      client: 'CloudScale Telemetry Group',
      role: 'Principal Systems Architect',
      metrics: [
        { value: '1.8M/s', label: 'Sustained Ingestion Rate' },
        { value: '4.2ms', label: 'p99 Range Query Latency' },
        { value: '-64%', label: 'Memory Footprint Reduction' }
      ],
      challenge: 'Legacy JSON-over-HTTP observability dashboards stalled when rendering more than 50,000 data points, causing browser main-thread lockups during incident triage.',
      solution: 'Designed a zero-allocation ring buffer in Rust compiled to WebAssembly, paired with Apache Arrow columnar streaming and offscreen Canvas rendering.',
      snippet: `// Chronos WASM Zero-Copy Columnar Slice
pub fn query_window(ptr: *const f64, len: usize, threshold: f64) -> usize {
    let slice = unsafe { std::slice::from_raw_parts(ptr, len) };
    slice.iter().filter(|&&sample| sample >= threshold).count()
}`,
      repoUrl: 'https://github.com/julianvance-arch/chronos-engine'
    },
    {
      id: 'aether-design-system',
      title: 'Aether Multi-Brand Token Compiler',
      category: 'interface',
      categoryLabel: 'Design Engineering',
      year: 2026,
      impactRank: 2,
      featured: true,
      bentoSpan: 'bento-compact',
      image: './assets/images/project-aether.svg',
      stack: 'TypeScript · CSS Custom Properties · AST',
      summary: 'Deterministic design token compiler and automated WCAG AAA contrast gate serving 48 accessible UI primitives with zero runtime JS overhead.',
      client: 'Meridian Financial Platform',
      role: 'Lead Design Technologist',
      metrics: [
        { value: '0 KB', label: 'CSS-in-JS Runtime Cost' },
        { value: '14.8:1', label: 'Primary Contrast Ratio' },
        { value: '48', label: 'Accessible Primitives' }
      ],
      challenge: 'Four product teams maintained divergent component libraries with inconsistent keyboard navigation and frequent dark-mode contrast regressions.',
      solution: 'Built an AST-based token compiler that transforms W3C Design Tokens into scoped CSS Custom Properties while failing CI builds if any surface pairing drops below WCAG AA/AAA thresholds.',
      snippet: `/* Generated by Aether Token Compiler v2.4 */
:root {
  --aether-surface-canvas: hsl(60 14% 95%);
  --aether-ink-primary: hsl(0 0% 7%);
  --aether-focus-ring: 2px solid hsl(221 83% 53%);
}`,
      repoUrl: 'https://github.com/julianvance-arch/aether-tokens'
    },
    {
      id: 'veritas-crdt',
      title: 'Veritas Local-First CRDT Document Canvas',
      category: 'systems',
      categoryLabel: 'Systems & Infrastructure',
      year: 2025,
      impactRank: 3,
      featured: true,
      bentoSpan: 'bento-compact',
      image: './assets/images/project-veritas.svg',
      stack: 'TypeScript · IndexedDB · WebRTC · Merkle-DAG',
      summary: 'Conflict-free replicated data type (CRDT) collaboration protocol enabling instant offline editing and deterministic peer-to-peer state convergence.',
      client: 'Veritas Research Labs',
      role: 'Core Protocol Engineer',
      metrics: [
        { value: '0ms', label: 'Local Commit Latency' },
        { value: '<15ms', label: 'P2P Merge Convergence' },
        { value: '2.1 MB', label: '100k Op State Footprint' }
      ],
      challenge: 'Distributed research teams working on field networks needed real-time collaborative specifications that functioned reliably across multi-hour offline intervals.',
      solution: 'Implemented a Hybrid Logical Clock (HLC) and run-length encoded LWW-Element-Set stored in IndexedDB with compact Merkle-tree delta synchronization.',
      snippet: `export function mergeClock(local: HLC, remote: HLC, now: number): HLC {
  const physical = Math.max(now, local.wall, remote.wall);
  const logical = (physical === local.wall && physical === remote.wall)
    ? Math.max(local.counter, remote.counter) + 1 : 0;
  return { wall: physical, counter: logical, node: local.node };
}`,
      repoUrl: 'https://github.com/julianvance-arch/veritas-crdt'
    },
    {
      id: 'kinetix-dsp',
      title: 'Kinetix WebGPU & Spatial Audio Synthesizer',
      category: 'interface',
      categoryLabel: 'Design Engineering',
      year: 2025,
      impactRank: 4,
      featured: true,
      bentoSpan: 'bento-wide',
      image: './assets/images/project-kinetix.svg',
      stack: 'WebAudio AudioWorklet · WebGPU · WGSL',
      summary: 'Lock-free real-time modal synthesis workstation running DSP audio graphs in a dedicated AudioWorklet thread with 120 FPS WebGPU spectrum shaders.',
      client: 'Sonora Acoustic Instruments',
      role: 'Creative Systems Engineer',
      metrics: [
        { value: '1.9ms', label: 'Audio Buffer Quantum' },
        { value: '120 FPS', label: 'WebGPU Shader Frame Lock' },
        { value: '64 Voices', label: 'Polyphonic Harmonics' }
      ],
      challenge: 'Browser-based audio tools suffered from garbage-collection glitches and UI frame drops when visualizing high-resolution FFT spectrum data.',
      solution: 'Decoupled the DSP synthesis kernel from the UI thread using SharedArrayBuffer ring buffers and rendered harmonic partials directly via WGSL compute shaders.',
      snippet: `// AudioWorklet Lock-Free Parameter Smoothing
for (let i = 0; i < outputChannel.length; i++) {
  currentGain += (targetGain - currentGain) * 0.0015;
  outputChannel[i] = Math.tanh(oscillatorSample(i) * currentGain);
}`,
      repoUrl: 'https://github.com/julianvance-arch/kinetix-dsp'
    },
    {
      id: 'lumina-docs',
      title: 'Lumina Zero-Dependency Static Docs Compiler',
      category: 'opensource',
      categoryLabel: 'Open Source Tooling',
      year: 2025,
      impactRank: 5,
      featured: false,
      bentoSpan: '',
      image: './assets/images/project-lumina.svg',
      stack: 'Vanilla JS · HTML5 · Precomputed Search Index',
      summary: 'Static documentation generator producing pure relative-path HTML bundles and a 14 KB client-side inverted search index optimized for GitHub Pages.',
      client: 'Open Source Community',
      role: 'Creator & Lead Maintainer',
      metrics: [
        { value: '100/100', label: 'Lighthouse Performance' },
        { value: '14.2 KB', label: 'Gzipped Search Index' },
        { value: '38ms', label: '420-Page Build Time' }
      ],
      challenge: 'Documentation sites hosted on GitHub Pages frequently broke under repository subdirectories due to absolute root asset paths and bloated SPA hydration.',
      solution: 'Engineered a relative-path link resolver and pre-built prefix trie index that delivers instant keyboard-accessible search without external API calls.',
      snippet: `// Relative Path Resolver for Subdirectory Deployments
export function resolveRelativeAsset(depth, relativeTarget) {
  const prefix = depth <= 0 ? './' : '../'.repeat(depth);
  return prefix + relativeTarget.replace(/^\\.\\//, '');
}`,
      repoUrl: 'https://github.com/julianvance-arch/lumina-docs'
    },
    {
      id: 'pulse-anycast',
      title: 'Pulse Anycast BGP & Edge Latency Visualizer',
      category: 'opensource',
      categoryLabel: 'Open Source Tooling',
      year: 2024,
      impactRank: 6,
      featured: false,
      bentoSpan: '',
      image: './assets/images/project-pulse.svg',
      stack: 'SVG Geometry · Canvas 2D · Streaming Telemetry',
      summary: 'Interactive network topology inspector mapping BGP route anomalies and edge PoP round-trip latency across 38 global regions.',
      client: 'Global Edge Collective',
      role: 'Principal Frontend Architect',
      metrics: [
        { value: '38 PoPs', label: 'Monitored Edge Regions' },
        { value: '<80ms', label: 'Anomaly Detection Lead' },
        { value: '60 FPS', label: 'Vector Arc Interpolation' }
      ],
      challenge: 'Network reliability engineers needed an uncluttered, high-contrast way to inspect BGP path shifts without wading through multi-megabyte WebGL globes.',
      solution: 'Crafted an orthographic SVG projection with tabular latency diff matrices and instant keyboard filtering by autonomous system number (ASN).',
      snippet: `// Great-Circle Quadratic Control Point Calculation
function computeArcControlPoint(p1, p2 curvature = 0.24) {
  const midX = (p1.x + p2.x) / 2;
  const midY = (p1.y + p2.y) / 2 - Math.hypot(p2.x - p1.x, p2.y - p1.y) * curvature;
  return { x: midX, y: midY };
}`,
      repoUrl: 'https://github.com/julianvance-arch/pulse-anycast'
    }
  ];

  /* --------------------------------------------------------------------------
   * 2. UTILITY HELPERS & TOAST NOTIFICATIONS
   * -------------------------------------------------------------------------- */
  function escapeHtml(str) {
    return String(str || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  let toastTimer = null;
  function showToast(message) {
    let toastEl = document.getElementById('site-toast');
    if (!toastEl) {
      toastEl = document.createElement('div');
      toastEl.id = 'site-toast';
      toastEl.className = 'toast-notification';
      toastEl.setAttribute('role', 'status');
      toastEl.setAttribute('aria-live', 'polite');
      document.body.appendChild(toastEl);
    }
    toastEl.textContent = message;
    toastEl.classList.add('is-visible');
    if (toastTimer) clearTimeout(toastTimer);
    toastTimer = setTimeout(function () {
      toastEl.classList.remove('is-visible');
    }, 3200);
  }

  function getStoredProjects() {
    try {
      const raw = localStorage.getItem(STORAGE_KEYS.PROJECTS);
      if (!raw) return DEFAULT_PROJECTS.slice();
      const parsed = JSON.parse(raw);
      return Array.isArray(parsed) && parsed.length > 0 ? parsed : DEFAULT_PROJECTS.slice();
    } catch (_err) {
      return DEFAULT_PROJECTS.slice();
    }
  }

  function saveStoredProjects(projects) {
    try {
      localStorage.setItem(STORAGE_KEYS.PROJECTS, JSON.stringify(projects));
    } catch (_err) {
      showToast('Browser storage quota reached.');
    }
  }

  /* --------------------------------------------------------------------------
   * 3. THEME MANAGEMENT (LIGHT / DARK)
   * -------------------------------------------------------------------------- */
  function initTheme() {
    let savedTheme = null;
    try {
      savedTheme = localStorage.getItem(STORAGE_KEYS.THEME);
    } catch (_e) {
      savedTheme = null;
    }

    const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
    const activeTheme = savedTheme || (prefersDark ? 'dark' : 'light');
    applyTheme(activeTheme);

    const toggleButtons = document.querySelectorAll('[data-action="toggle-theme"]');
    toggleButtons.forEach(function (btn) {
      btn.addEventListener('click', function () {
        const current = document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'light';
        const next = current === 'dark' ? 'light' : 'dark';
        applyTheme(next);
        try {
          localStorage.setItem(STORAGE_KEYS.THEME, next);
        } catch (_e) {
          /* ignore private browsing restriction */
        }
        showToast(next === 'dark' ? 'Dark editorial theme enabled' : 'Light architectural theme enabled');
      });
    });
  }

  function applyTheme(theme) {
    if (theme === 'dark') {
      document.documentElement.setAttribute('data-theme', 'dark');
    } else {
      document.documentElement.removeAttribute('data-theme');
    }

    const toggleButtons = document.querySelectorAll('[data-action="toggle-theme"]');
    toggleButtons.forEach(function (btn) {
      const label = theme === 'dark' ? 'Switch to light theme' : 'Switch to dark theme';
      btn.setAttribute('aria-label', label);
      btn.setAttribute('title', label);
      const iconSpan = btn.querySelector('[data-theme-icon]');
      if (iconSpan) {
        iconSpan.textContent = theme === 'dark' ? '☀' : '☾';
      }
    });
  }

  /* --------------------------------------------------------------------------
   * 4. MOBILE NAVIGATION DRAWER
   * -------------------------------------------------------------------------- */
  function initMobileNav() {
    const toggleBtn = document.getElementById('mobile-menu-toggle');
    const drawer = document.getElementById('mobile-nav-drawer');
    if (!toggleBtn || !drawer) return;

    function closeMenu() {
      toggleBtn.setAttribute('aria-expanded', 'false');
      drawer.classList.remove('is-open');
      const icon = toggleBtn.querySelector('[data-menu-icon]');
      if (icon) icon.textContent = '☰';
    }

    toggleBtn.addEventListener('click', function () {
      const expanded = toggleBtn.getAttribute('aria-expanded') === 'true';
      if (expanded) {
        closeMenu();
      } else {
        toggleBtn.setAttribute('aria-expanded', 'true');
        drawer.classList.add('is-open');
        const icon = toggleBtn.querySelector('[data-menu-icon]');
        if (icon) icon.textContent = '✕';
      }
    });

    drawer.querySelectorAll('a').forEach(function (link) {
      link.addEventListener('click', closeMenu);
    });

    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && drawer.classList.contains('is-open')) {
        closeMenu();
        toggleBtn.focus();
      }
    });
  }

  /* --------------------------------------------------------------------------
   * 5. HOME PAGE: PORTFOLIO GRID, FILTER, SEARCH, MODAL & CUSTOM PROJECT CRUD
   * -------------------------------------------------------------------------- */
  function initPortfolioCatalog() {
    const gridEl = document.getElementById('projects-bento-grid');
    if (!gridEl) return;

    let projects = getStoredProjects();
    let currentFilter = 'all';
    let currentSearch = '';
    let currentSort = 'featured';
    let activeModalProjectId = null;

    const filterBtns = document.querySelectorAll('[data-filter]');
    const searchInput = document.getElementById('project-search');
    const searchClearBtn = document.getElementById('project-search-clear');
    const sortSelect = document.getElementById('project-sort');
    const countLabel = document.getElementById('projects-count-label');

    function getFilteredProjects() {
      return projects
        .filter(function (p) {
          const matchesCategory = currentFilter === 'all' || p.category === currentFilter;
          const q = currentSearch.trim().toLowerCase();
          const matchesQuery =
            !q ||
            p.title.toLowerCase().includes(q) ||
            p.summary.toLowerCase().includes(q) ||
            p.stack.toLowerCase().includes(q) ||
            p.categoryLabel.toLowerCase().includes(q);
          return matchesCategory && matchesQuery;
        })
        .sort(function (a, b) {
          if (currentSort === 'newest') return b.year - a.year;
          if (currentSort === 'impact') return (a.impactRank || 99) - (b.impactRank || 99);
          return (b.featured ? 1 : 0) - (a.featured ? 1 : 0);
        });
    }

    function renderGrid() {
      const visible = getFilteredProjects();
      if (countLabel) {
        countLabel.textContent =
          'Showing ' + visible.length + ' of ' + projects.length + ' architectural case studies';
      }

      if (visible.length === 0) {
        gridEl.innerHTML =
          '<div class="empty-state-box">' +
          '<h3 class="heading-md">No matching case studies found</h3>' +
          '<p class="body-md" style="margin: 8px auto 20px;">Try clearing your search query or switching back to All Works.</p>' +
          '<button type="button" class="btn btn-outline" id="reset-catalog-filters">Reset Filters</button>' +
          '</div>';
        const resetBtn = document.getElementById('reset-catalog-filters');
        if (resetBtn) {
          resetBtn.addEventListener('click', function () {
            currentFilter = 'all';
            currentSearch = '';
            currentSort = 'featured';
            if (searchInput) searchInput.value = '';
            if (searchClearBtn) searchClearBtn.classList.remove('is-visible');
            if (sortSelect) sortSelect.value = 'featured';
            filterBtns.forEach(function (b) {
              b.classList.toggle('is-active', b.getAttribute('data-filter') === 'all');
            });
            renderGrid();
          });
        }
        return;
      }

      gridEl.innerHTML = visible
        .map(function (project) {
          const spanClass = currentFilter === 'all' && !currentSearch && project.bentoSpan ? ' ' + project.bentoSpan : '';
          const primaryMetric =
            project.metrics && project.metrics[0]
              ? project.metrics[0].value + ' ' + project.metrics[0].label
              : project.role;

          return (
            '<article class="project-card' +
            spanClass +
            '" data-project-id="' +
            escapeHtml(project.id) +
            '">' +
            '<div>' +
            '<div class="project-media-wrap" role="button" tabindex="0" data-open-case="' +
            escapeHtml(project.id) +
            '" aria-label="Inspect case study for ' +
            escapeHtml(project.title) +
            '">' +
            '<img src="' +
            escapeHtml(project.image) +
            '" alt="' +
            escapeHtml(project.title) +
            ' preview diagram" loading="lazy" width="1200" height="750" />' +
            '</div>' +
            '<div class="project-body" style="margin-top: 16px;">' +
            '<div class="meta-inline">' +
            '<span>' +
            escapeHtml(project.categoryLabel) +
            '</span>' +
            '<span class="meta-sep" aria-hidden="true">·</span>' +
            '<span class="tabular-nums">' +
            escapeHtml(project.year) +
            '</span>' +
            '<span class="meta-sep" aria-hidden="true">·</span>' +
            '<span>' +
            escapeHtml(project.stack) +
            '</span>' +
            '</div>' +
            '<div class="project-title-row">' +
            '<h3 class="project-title">' +
            '<button type="button" class="project-title-btn" data-open-case="' +
            escapeHtml(project.id) +
            '">' +
            escapeHtml(project.title) +
            '</button>' +
            '</h3>' +
            '</div>' +
            '<p class="project-summary">' +
            escapeHtml(project.summary) +
            '</p>' +
            '</div>' +
            '</div>' +
            '<div class="project-footer">' +
            '<span class="meta-inline tabular-nums">' +
            escapeHtml(primaryMetric) +
            '</span>' +
            '<div style="display:flex; align-items:center; gap: 12px;">' +
            (project.isCustom
              ? '<button type="button" class="text-action-link" style="color: var(--status-error);" data-delete-project="' +
                escapeHtml(project.id) +
                '">Delete</button>'
              : '') +
            '<button type="button" class="text-action-link" data-open-case="' +
            escapeHtml(project.id) +
            '">Inspect Case Study →</button>' +
            '</div>' +
            '</div>' +
            '</article>'
          );
        })
        .join('');

      gridEl.querySelectorAll('[data-open-case]').forEach(function (trigger) {
        trigger.addEventListener('click', function () {
          const id = trigger.getAttribute('data-open-case');
          openCaseStudyModal(id);
        });
        trigger.addEventListener('keydown', function (e) {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            openCaseStudyModal(trigger.getAttribute('data-open-case'));
          }
        });
      });

      gridEl.querySelectorAll('[data-delete-project]').forEach(function (delBtn) {
        delBtn.addEventListener('click', function (e) {
          e.stopPropagation();
          const targetId = delBtn.getAttribute('data-delete-project');
          projects = projects.filter(function (p) {
            return p.id !== targetId;
          });
          saveStoredProjects(projects);
          renderGrid();
          showToast('Custom project removed from LocalStorage');
        });
      });
    }

    filterBtns.forEach(function (btn) {
      btn.addEventListener('click', function () {
        currentFilter = btn.getAttribute('data-filter') || 'all';
        filterBtns.forEach(function (b) {
          b.classList.toggle('is-active', b === btn);
        });
        renderGrid();
      });
    });

    if (searchInput) {
      searchInput.addEventListener('input', function () {
        currentSearch = searchInput.value;
        if (searchClearBtn) {
          searchClearBtn.classList.toggle('is-visible', currentSearch.length > 0);
        }
        renderGrid();
      });
    }

    if (searchClearBtn && searchInput) {
      searchClearBtn.addEventListener('click', function () {
        searchInput.value = '';
        currentSearch = '';
        searchClearBtn.classList.remove('is-visible');
        searchInput.focus();
        renderGrid();
      });
    }

    if (sortSelect) {
      sortSelect.addEventListener('change', function () {
        currentSort = sortSelect.value;
        renderGrid();
      });
    }

    /* Case Study Modal Logic */
    const caseModal = document.getElementById('case-study-modal');
    const caseModalContent = document.getElementById('case-study-modal-body');
    const caseCloseBtn = document.getElementById('close-case-modal');
    const prevCaseBtn = document.getElementById('prev-case-btn');
    const nextCaseBtn = document.getElementById('next-case-btn');

    function openCaseStudyModal(projectId) {
      if (!caseModal || !caseModalContent) return;
      const project = projects.find(function (p) {
        return p.id === projectId;
      });
      if (!project) return;
      activeModalProjectId = project.id;

      const metricsHtml = (project.metrics || [])
        .map(function (m) {
          return (
            '<div>' +
            '<div class="metric-value tabular-nums">' +
            escapeHtml(m.value) +
            '</div>' +
            '<div class="metric-label">' +
            escapeHtml(m.label) +
            '</div>' +
            '</div>'
          );
        })
        .join('');

      caseModalContent.innerHTML =
        '<div class="meta-inline" style="margin-bottom: 10px;">' +
        '<span>' +
        escapeHtml(project.categoryLabel) +
        '</span>' +
        '<span class="meta-sep">·</span>' +
        '<span class="tabular-nums">' +
        escapeHtml(project.year) +
        '</span>' +
        '<span class="meta-sep">·</span>' +
        '<span>Client: ' +
        escapeHtml(project.client || 'Independent Architecture') +
        '</span>' +
        '<span class="meta-sep">·</span>' +
        '<span>Role: ' +
        escapeHtml(project.role || 'Lead Architect') +
        '</span>' +
        '</div>' +
        '<h2 class="display-lg" style="margin-bottom: 16px;">' +
        escapeHtml(project.title) +
        '</h2>' +
        '<p class="body-lg" style="margin-bottom: 20px;">' +
        escapeHtml(project.summary) +
        '</p>' +
        '<div class="project-media-wrap" style="cursor: default; margin-bottom: 20px;">' +
        '<img src="' +
        escapeHtml(project.image) +
        '" alt="' +
        escapeHtml(project.title) +
        '" width="1200" height="750" />' +
        '</div>' +
        '<div class="modal-metrics-row">' +
        metricsHtml +
        '</div>' +
        '<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 24px; margin-top: 24px;">' +
        '<div>' +
        '<h3 class="heading-md" style="margin-bottom: 8px;">01. Architectural Challenge</h3>' +
        '<p class="body-md">' +
        escapeHtml(project.challenge) +
        '</p>' +
        '</div>' +
        '<div>' +
        '<h3 class="heading-md" style="margin-bottom: 8px;">02. Engineering Solution</h3>' +
        '<p class="body-md">' +
        escapeHtml(project.solution) +
        '</p>' +
        '</div>' +
        '</div>' +
        (project.snippet
          ? '<div style="margin-top: 24px;">' +
            '<div style="display:flex; justify-content:space-between; align-items:center;">' +
            '<span class="kicker" style="margin-bottom:0;">IMPLEMENTATION EXCERPT · ' +
            escapeHtml(project.stack) +
            '</span>' +
            '<button type="button" class="text-action-link" id="copy-snippet-btn">Copy Code</button>' +
            '</div>' +
            '<pre class="modal-code-block"><code>' +
            escapeHtml(project.snippet) +
            '</code></pre>' +
            '</div>'
          : '');

      const copySnippetBtn = document.getElementById('copy-snippet-btn');
      if (copySnippetBtn && project.snippet) {
        copySnippetBtn.addEventListener('click', function () {
          if (navigator.clipboard && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(project.snippet).then(function () {
              showToast('Implementation snippet copied to clipboard');
            });
          } else {
            showToast('Code copied');
          }
        });
      }

      caseModal.classList.add('is-open');
      caseModal.setAttribute('aria-hidden', 'false');
      if (caseCloseBtn) caseCloseBtn.focus();
    }

    function closeCaseStudyModal() {
      if (!caseModal) return;
      caseModal.classList.remove('is-open');
      caseModal.setAttribute('aria-hidden', 'true');
      activeModalProjectId = null;
    }

    function cycleCaseStudy(direction) {
      const list = getFilteredProjects();
      if (list.length === 0 || !activeModalProjectId) return;
      const idx = list.findIndex(function (p) {
        return p.id === activeModalProjectId;
      });
      if (idx === -1) return;
      const nextIdx = (idx + direction + list.length) % list.length;
      openCaseStudyModal(list[nextIdx].id);
    }

    if (caseCloseBtn) caseCloseBtn.addEventListener('click', closeCaseStudyModal);
    if (prevCaseBtn) {
      prevCaseBtn.addEventListener('click', function () {
        cycleCaseStudy(-1);
      });
    }
    if (nextCaseBtn) {
      nextCaseBtn.addEventListener('click', function () {
        cycleCaseStudy(1);
      });
    }
    if (caseModal) {
      caseModal.addEventListener('click', function (e) {
        if (e.target === caseModal) closeCaseStudyModal();
      });
    }

    /* Add Custom Project Modal (LocalStorage Browser Demo) */
    const addProjectModal = document.getElementById('add-project-modal');
    const openAddProjectBtns = document.querySelectorAll('[data-action="open-add-project"]');
    const closeAddProjectBtn = document.getElementById('close-add-project-modal');
    const addProjectForm = document.getElementById('add-project-form');
    const resetProjectsBtn = document.getElementById('reset-default-projects');

    function closeAddModal() {
      if (!addProjectModal) return;
      addProjectModal.classList.remove('is-open');
      addProjectModal.setAttribute('aria-hidden', 'true');
    }

    openAddProjectBtns.forEach(function (btn) {
      btn.addEventListener('click', function () {
        if (!addProjectModal) return;
        addProjectModal.classList.add('is-open');
        addProjectModal.setAttribute('aria-hidden', 'false');
        const firstInput = document.getElementById('new-project-title');
        if (firstInput) firstInput.focus();
      });
    });

    if (closeAddProjectBtn) {
      closeAddProjectBtn.addEventListener('click', closeAddModal);
    }
    if (addProjectModal) {
      addProjectModal.addEventListener('click', function (e) {
        if (e.target === addProjectModal) closeAddModal();
      });
    }

    if (addProjectForm) {
      addProjectForm.addEventListener('submit', function (e) {
        e.preventDefault();
        const title = document.getElementById('new-project-title').value.trim();
        const category = document.getElementById('new-project-category').value;
        const stack = document.getElementById('new-project-stack').value.trim();
        const metricVal = document.getElementById('new-project-metric').value.trim();
        const summary = document.getElementById('new-project-summary').value.trim();
        const imageChoice = document.getElementById('new-project-image').value;

        if (!title || !stack || !summary) {
          showToast('Please complete all required project fields.');
          return;
        }

        const categoryMap = {
          systems: 'Systems & Infrastructure',
          interface: 'Design Engineering',
          opensource: 'Open Source Tooling'
        };

        const newEntry = {
          id: 'custom-' + Date.now(),
          title: title,
          category: category,
          categoryLabel: categoryMap[category] || 'Systems & Infrastructure',
          year: new Date().getFullYear(),
          impactRank: 1,
          featured: true,
          bentoSpan: '',
          image: imageChoice || './assets/images/project-chronos.svg',
          stack: stack,
          summary: summary,
          client: 'Custom Portfolio Entry',
          role: 'Lead Engineer',
          isCustom: true,
          metrics: [
            { value: metricVal || '100%', label: 'Primary Impact Metric' },
            { value: '2026', label: 'Release Year' },
            { value: 'Local', label: 'Saved in Browser Storage' }
          ],
          challenge: 'Custom case study added via the interactive browser portfolio manager.',
          solution: summary,
          snippet: '// Custom Project Entry (' + title + ')\n// Stored in localStorage for static GitHub Pages persistence.'
        };

        projects.unshift(newEntry);
        saveStoredProjects(projects);
        addProjectForm.reset();
        closeAddModal();
        renderGrid();
        showToast('Project "' + title + '" added to portfolio!');
      });
    }

    if (resetProjectsBtn) {
      resetProjectsBtn.addEventListener('click', function () {
        localStorage.removeItem(STORAGE_KEYS.PROJECTS);
        projects = DEFAULT_PROJECTS.slice();
        renderGrid();
        closeAddModal();
        showToast('Portfolio reset to default 6 case studies');
      });
    }

    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') {
        if (caseModal && caseModal.classList.contains('is-open')) closeCaseStudyModal();
        if (addProjectModal && addProjectModal.classList.contains('is-open')) closeAddModal();
      } else if (caseModal && caseModal.classList.contains('is-open')) {
        if (e.key === 'ArrowLeft') cycleCaseStudy(-1);
        if (e.key === 'ArrowRight') cycleCaseStudy(1);
      }
    });

    renderGrid();
  }

  /* --------------------------------------------------------------------------
   * 6. ABOUT PAGE: INTERACTIVE TIMELINE, SKILLS FILTER & RESUME EXPORT
   * -------------------------------------------------------------------------- */
  function initAboutPage() {
    const timelineToggles = document.querySelectorAll('[data-toggle-timeline]');
    timelineToggles.forEach(function (btn) {
      btn.addEventListener('click', function () {
        const targetId = btn.getAttribute('data-toggle-timeline');
        const targetEl = document.getElementById(targetId);
        if (!targetEl) return;
        const isOpen = targetEl.classList.toggle('is-open');
        btn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
        btn.textContent = isOpen ? 'Hide Architectural Notes ↑' : 'Read Architectural Notes ↓';
      });
    });

    const skillFilterBtns = document.querySelectorAll('[data-skill-filter]');
    const skillRows = document.querySelectorAll('[data-skill-domain]');
    skillFilterBtns.forEach(function (btn) {
      btn.addEventListener('click', function () {
        const domain = btn.getAttribute('data-skill-filter');
        skillFilterBtns.forEach(function (b) {
          b.classList.toggle('is-active', b === btn);
        });
        skillRows.forEach(function (row) {
          const rowDomain = row.getAttribute('data-skill-domain');
          row.style.display = domain === 'all' || rowDomain === domain ? '' : 'none';
        });
      });
    });

    const printResumeBtn = document.getElementById('print-resume-btn');
    if (printResumeBtn) {
      printResumeBtn.addEventListener('click', function () {
        window.print();
      });
    }

    const downloadResumeBtn = document.getElementById('download-resume-md-btn');
    if (downloadResumeBtn) {
      downloadResumeBtn.addEventListener('click', function () {
        const markdown = [
          '# Julian Vance — Principal Systems Architect & Design Technologist',
          'Location: San Francisco, CA | Email: julian.vance@architect.dev | Web: GitHub Pages Portfolio',
          '',
          '## Executive Summary',
          'Principal Systems Architect and Design Engineer with 8+ years building high-throughput distributed telemetry engines, local-first CRDT protocols, and WCAG AAA design systems.',
          '',
          '## Experience',
          '- **Principal Systems Architect — CloudScale Telemetry Group (2023–Present)**',
          '  Architected Chronos Rust/WASM columnar engine (1.8M writes/sec, 4.2ms p99 latency).',
          '- **Lead Design Technologist — Meridian Financial Platform (2021–2023)**',
          '  Created Aether Token Compiler serving 48 zero-runtime accessible primitives across 4 product suites.',
          '- **Senior Frontend & Protocol Engineer — Veritas Research Labs (2018–2021)**',
          '  Built local-first IndexedDB + WebRTC collaborative canvas with deterministic CRDT merge.',
          '',
          '## Core Technical Capabilities',
          '- Systems & Languages: Rust, TypeScript, modern JavaScript (ES2024+), WebAssembly, SQL, C++',
          '- Frontend & Design Systems: Semantic HTML5, CSS3 Architecture, WebGPU/Canvas, Accessibility (WCAG AAA)',
          '- Distributed Protocols: CRDTs, Apache Arrow IPC, WebRTC DataChannels, Edge Anycast Telemetry'
        ].join('\n');

        const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'Julian_Vance_Resume_2026.md';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        showToast('Resume downloaded as Julian_Vance_Resume_2026.md');
      });
    }
  }

  /* --------------------------------------------------------------------------
   * 7. CONTACT PAGE: VALIDATION, COPY EMAIL & LOCALSTORAGE INBOX
   * -------------------------------------------------------------------------- */
  function initContactPage() {
    const copyEmailBtns = document.querySelectorAll('[data-copy-email]');
    copyEmailBtns.forEach(function (btn) {
      btn.addEventListener('click', function () {
        const email = btn.getAttribute('data-copy-email') || 'julian.vance@architect.dev';
        if (navigator.clipboard && navigator.clipboard.writeText) {
          navigator.clipboard.writeText(email).then(function () {
            showToast('Copied ' + email + ' to clipboard');
          });
        } else {
          showToast('Email address: ' + email);
        }
      });
    });

    const form = document.getElementById('contact-inquiry-form');
    const inboxContainer = document.getElementById('local-inquiries-list');
    const inboxCountEl = document.getElementById('inquiries-count-badge');
    const exportJsonBtn = document.getElementById('export-inquiries-json');
    const clearInquiriesBtn = document.getElementById('clear-all-inquiries');
    const successBanner = document.getElementById('contact-success-banner');

    function getInquiries() {
      try {
        const raw = localStorage.getItem(STORAGE_KEYS.INQUIRIES);
        if (!raw) return [];
        const parsed = JSON.parse(raw);
        return Array.isArray(parsed) ? parsed : [];
      } catch (_e) {
        return [];
      }
    }

    function saveInquiries(list) {
      try {
        localStorage.setItem(STORAGE_KEYS.INQUIRIES, JSON.stringify(list));
      } catch (_e) {
        showToast('Unable to save inquiry in private browsing mode.');
      }
    }

    function renderInquiries() {
      if (!inboxContainer) return;
      const list = getInquiries();
      if (inboxCountEl) {
        inboxCountEl.textContent = list.length + (list.length === 1 ? ' saved inquiry' : ' saved inquiries');
      }

      if (list.length === 0) {
        inboxContainer.innerHTML =
          '<div class="inbox-item" style="text-align:center; padding: 32px;">' +
          '<p class="body-md" style="margin: 0 auto;">No local inquiries stored yet. Submit the form above to test browser-side persistence and mailto dispatch.</p>' +
          '</div>';
        return;
      }

      inboxContainer.innerHTML = list
        .map(function (item) {
          const mailtoHref =
            'mailto:julian.vance@architect.dev?subject=' +
            encodeURIComponent('[Portfolio Inquiry] ' + item.scope + ' — ' + item.name) +
            '&body=' +
            encodeURIComponent(
              'Name: ' +
                item.name +
                '\nEmail: ' +
                item.email +
                '\nScope: ' +
                item.scope +
                '\nTimeline / Budget: ' +
                item.budget +
                '\n\nMessage:\n' +
                item.message
            );

          return (
            '<article class="inbox-item">' +
            '<div class="inbox-item-header">' +
            '<div>' +
            '<strong style="font-size: 1rem;">' +
            escapeHtml(item.name) +
            '</strong>' +
            '<span class="meta-inline" style="display:inline-flex; margin-left: 10px;">' +
            '<span>' +
            escapeHtml(item.email) +
            '</span>' +
            '<span class="meta-sep">·</span>' +
            '<span>' +
            escapeHtml(item.scope) +
            '</span>' +
            '<span class="meta-sep">·</span>' +
            '<span class="tabular-nums">' +
            escapeHtml(item.budget) +
            '</span>' +
            '</span>' +
            '</div>' +
            '<span class="meta-inline tabular-nums">' +
            escapeHtml(item.timestamp) +
            '</span>' +
            '</div>' +
            '<p class="body-md">' +
            escapeHtml(item.message) +
            '</p>' +
            '<div style="display:flex; flex-wrap:wrap; align-items:center; gap: 16px; padding-top: 8px;">' +
            '<a href="' +
            mailtoHref +
            '" class="text-action-link">Launch in Email Client (mailto:) →</a>' +
            '<button type="button" class="text-action-link" style="color: var(--status-error);" data-delete-inquiry="' +
            escapeHtml(item.id) +
            '">Delete Record</button>' +
            '</div>' +
            '</article>'
          );
        })
        .join('');

      inboxContainer.querySelectorAll('[data-delete-inquiry]').forEach(function (btn) {
        btn.addEventListener('click', function () {
          const id = btn.getAttribute('data-delete-inquiry');
          const updated = getInquiries().filter(function (i) {
            return i.id !== id;
          });
          saveInquiries(updated);
          renderInquiries();
          showToast('Inquiry deleted from LocalStorage');
        });
      });
    }

    if (form) {
      form.addEventListener('submit', function (e) {
        e.preventDefault();
        const nameInput = document.getElementById('contact-name');
        const emailInput = document.getElementById('contact-email');
        const scopeInput = document.getElementById('contact-scope');
        const budgetInput = document.getElementById('contact-budget');
        const messageInput = document.getElementById('contact-message');

        let isValid = true;
        function setFieldState(inputEl, errorId, condition) {
          const errEl = document.getElementById(errorId);
          if (!condition) {
            isValid = false;
            if (inputEl) inputEl.classList.add('has-error');
            if (errEl) errEl.classList.add('is-visible');
          } else {
            if (inputEl) inputEl.classList.remove('has-error');
            if (errEl) errEl.classList.remove('is-visible');
          }
        }

        const nameVal = nameInput ? nameInput.value.trim() : '';
        const emailVal = emailInput ? emailInput.value.trim() : '';
        const messageVal = messageInput ? messageInput.value.trim() : '';
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

        setFieldState(nameInput, 'error-contact-name', nameVal.length >= 2);
        setFieldState(emailInput, 'error-contact-email', emailRegex.test(emailVal));
        setFieldState(messageInput, 'error-contact-message', messageVal.length >= 15);

        if (!isValid) {
          showToast('Please check the highlighted form fields.');
          return;
        }

        const newInquiry = {
          id: 'inq-' + Date.now(),
          name: nameVal,
          email: emailVal,
          scope: scopeInput ? scopeInput.value : 'Systems Architecture',
          budget: budgetInput ? budgetInput.value : '$15k – $30k',
          message: messageVal,
          timestamp: new Date().toISOString().slice(0, 16).replace('T', ' ') + ' UTC'
        };

        const list = getInquiries();
        list.unshift(newInquiry);
        saveInquiries(list);
        form.reset();

        if (successBanner) {
          successBanner.classList.add('is-success');
          successBanner.textContent =
            'Inquiry validated and saved to your browser LocalStorage inbox below. You can also dispatch it directly via your email client.';
        }
        renderInquiries();
        showToast('Inquiry saved to LocalStorage inbox!');
      });
    }

    if (exportJsonBtn) {
      exportJsonBtn.addEventListener('click', function () {
        const list = getInquiries();
        if (list.length === 0) {
          showToast('No saved inquiries to export.');
          return;
        }
        const blob = new Blob([JSON.stringify(list, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'portfolio-inquiries-export.json';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        showToast('Exported ' + list.length + ' inquiries as JSON');
      });
    }

    if (clearInquiriesBtn) {
      clearInquiriesBtn.addEventListener('click', function () {
        localStorage.removeItem(STORAGE_KEYS.INQUIRIES);
        renderInquiries();
        if (successBanner) successBanner.classList.remove('is-success');
        showToast('Cleared all saved inquiries from LocalStorage');
      });
    }

    renderInquiries();
  }

  /* --------------------------------------------------------------------------
   * 8. INITIALIZE ON DOM READY
   * -------------------------------------------------------------------------- */
  document.addEventListener('DOMContentLoaded', function () {
    initTheme();
    initMobileNav();
    initPortfolioCatalog();
    initAboutPage();
    initContactPage();
  });
})();
